### ISSUE TITLE
NameError: name 'classifier' is not defined for training a new model

### ISSUE THREAD

**Issue by fmehralian** [tech-srl/counting_dimensions#1]
First, thanks for making your code publicly available. 
I have an issue in training a new model. 
<img width="1011" alt="Screen Shot 2019-05-22 at 2 13 17 PM" src="https://user-images.githubusercontent.com/8522977/58209522-132d7780-7c9c-11e9-953e-5b56ca774ee7.png">
What should the '_classifier_' be?

**Comment by gailweiss** [comment]
Hi Forough,

Thank you for pointing out this mistake!
The classifier should be a boolean function that classifies whether sequences do or do not belong to the target language. It should be passed to the function train_network_on_positive_words  as an optional parameter (this was missing in the colab file).

I have updated  train_network_on_positive_words, and added the use of 'classifier' to the example. Please update me if this does not fix your problem

Good luck,
Gail



________________________________

**Comment by fmehralian** [comment]
Thanks for your prompt response and correction. Just as a suggestion, it would be good to update the notebook in your repository as well.

**Comment by gailweiss** [comment]
You are right, I will do this as well (update: done)
